In [1]:

from pprint import pprint
import pathlib
import resourcesdb

In [2]:
bdf = resourcesdb.getResourcesFrame()

In [3]:
bdf.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [4]:
csb = bdf[(bdf.studying_now == True)]

In [6]:
csb.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [15]:
b = csb.iloc[0]

In [19]:
b.duration
b.status

10

In [20]:
b.name

'id_0001'

In [21]:
b

duration                                                       422
link                            https://www.openintro.org/book/os/
main_category                           Probability and Statistics
name                                          OpenIntro Statistics
status                                                          10
studying_now                                                  True
tags             [math, statistics, probability, introductory, ...
type                                                          book
Name: id_0001, dtype: object

In [22]:
b.loc['name']

'OpenIntro Statistics'

In [23]:
def printBookStatus(bookDF):
    """ return string of current book stats """

    totalPages = bookDF.loc['duration']
    currentPage = bookDF.loc['status']
    name = bookDF.loc['name']

    print()
    print(f" {name} ".center(70, '='))
    print(f"· totalPages:\t{totalPages}")
    print(f"· currentPage:\t{totalPages}")
    print()

In [24]:
printBookStatus(b)

======================== OpenIntro Statistics ========================
· totalPages:	422
· currentPage:	422

In [25]:
len(csb)

5

In [27]:
csb.iloc[0]

duration                                                       422
link                            https://www.openintro.org/book/os/
main_category                           Probability and Statistics
name                                          OpenIntro Statistics
status                                                          10
studying_now                                                  True
tags             [math, statistics, probability, introductory, ...
type                                                          book
Name: id_0001, dtype: object

In [31]:
for f in range(len(csb)):
    print('*'*70)
    print(csb.iloc[f])
    print()

**********************************************************************
duration                                                       422
link                            https://www.openintro.org/book/os/
main_category                           Probability and Statistics
name                                          OpenIntro Statistics
status                                                          10
studying_now                                                  True
tags             [math, statistics, probability, introductory, ...
type                                                          book
Name: id_0001, dtype: object

**********************************************************************
duration                                                      247
link                    https://rstudio-education.github.io/hopr/
main_category                                                   R
name                                   HandsOn Programming with R
status                                                         17
studying_now                                                 True
tags             [programming, Computer Science, introductory, R]
type                                                         book
Name: id_0002, dtype: object

**********************************************************************
duration                                                       469
link             https://www.edx.org/course/linear-algebra-foun...
main_category                                       Linear Algebra
name                     Linear Algebra - Foundations to Frontiers
status                                                          40
studying_now                                                  True
tags             [Linear Algebra, math, Computer Science, intro...
type                                                          book
Name: id_0003, dtype: object

**********************************************************************
duration                                                       548
link             https://jakevdp.github.io/PythonDataScienceHan...
main_category                                               Python
name                                  Python Data Science Handbook
status                                                          68
studying_now                                                  True
tags             [Python, Computer Science, Data Science, intro...
type                                                          book
Name: id_0004, dtype: object

**********************************************************************
duration                                                       520
link                      https://r4ds.had.co.nz/introduction.html
main_category                                                    R
name                                            R for Data Science
status                                                          40
studying_now                                                  True
tags             [programming, Computer Science, introductory, ...
type                                                          book
Name: id_0005, dtype: object

In [37]:
b.name

'id_0001'

In [42]:
d = bdf.copy()
d.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [46]:
d.at[b.name, 'duration'] = 10
d.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,10,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [50]:
type(d.loc['id_0001']['duration'])

int

In [51]:
bdf.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [52]:
b

duration                                                       422
link                            https://www.openintro.org/book/os/
main_category                           Probability and Statistics
name                                          OpenIntro Statistics
status                                                          10
studying_now                                                  True
tags             [math, statistics, probability, introductory, ...
type                                                          book
Name: id_0001, dtype: object

In [53]:
b.loc['status']

10

In [54]:
bdf.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [55]:
csb.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [56]:
bdf.at['id_0001', 'status'] = 200

In [57]:
bdf.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,200,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [58]:
csb.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,10,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [59]:
bdf.head()

,duration,link,main_category,name,status,studying_now,tags,type
id_0001,422,https://www.openintro.org/book/os/,Probability and Statistics,OpenIntro Statistics,200,True,"[math, statistics, probability, introductory, ...",book
id_0002,247,https://rstudio-education.github.io/hopr/,R,HandsOn Programming with R,17,True,"[programming, Computer Science, introductory, R]",book
id_0003,469,https://www.edx.org/course/linear-algebra-foun...,Linear Algebra,Linear Algebra - Foundations to Frontiers,40,True,"[Linear Algebra, math, Computer Science, intro...",book
id_0004,548,https://jakevdp.github.io/PythonDataScienceHan...,Python,Python Data Science Handbook,68,True,"[Python, Computer Science, Data Science, intro...",book
id_0005,520,https://r4ds.had.co.nz/introduction.html,R,R for Data Science,40,True,"[programming, Computer Science, introductory, ...",book

In [62]:
g = bdf.T.to_dict()

In [64]:
import collections

g = collections.defaultdict(dict, g)

In [69]:
def convertDataFrameToDict(bdf):

    return collections.defaultdict(dict, bdf.T.to_dict())

In [71]:
convertDataFrameToDict(bdf)['id_0020']

{'duration': 4,
 'link': 'https://www.coursera.org/learn/algorithms-npcomplete',
 'main_category': 'Algorithms',
 'name': 'Algorithms 04 - Shortest Paths Revisited, NP-Complete Problems and What To Do About Them',
 'status': 0,
 'studying_now': False,
 'tags': ['Algorithms', 'math', 'Computer Science', 'programming'],
 'type': 'mooc'}